---
authors:
  - geerlingguy (https://www.jeffgeerling.com/)
  - fabianvf (https://github.com/fabianvf)
  - willthames (https://github.com/willthames)
  - Akasurde (https://github.com/akasurde)
dependencies:
  kubernetes.core: '>=2.1.0,<2.2.0'
description: OKD Collection for Ansible.
documentation: ''
homepage: ''
issues: https://github.com/ansible-collections/community.okd/issues
license_file: LICENSE
name: okd
namespace: community
readme: README.md
repository: https://github.com/ansible-collections/community.okd
tags:
  - kubernetes
  - k8s
  - cloud
  - infrastructure
  - openshift
  - okd
  - cluster
# Also needs to be updated in the Makefile
version: 2.0.1
