---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  log: true
  options:
    vvv: True
  config_options:
    inventory:
      enable_plugins: community.okd.openshift
  lint: |
    set -e
    ansible-lint
  inventory:
    hosts:
      plugin: community.okd.openshift
    host_vars:
      localhost:
        virtualenv: ${MOLECULE_EPHEMERAL_DIRECTORY}/virtualenv
        virtualenv_command: '{{ ansible_playbook_python }} -m virtualenv'
        virtualenv_interpreter: '{{ virtualenv }}/bin/python'
        playbook_namespace: molecule-tests
  env:
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_COLLECTIONS_PATHS: ${OVERRIDE_COLLECTION_PATH:-$MOLECULE_PROJECT_DIRECTORY}
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - syntax
    - prepare
    - converge
    - idempotence
    - verify
